name: ciao
run-name: ciao da parte di ${{ github.actor }}
on: [push]
jobs:
  ciao-fa-cose:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fineeeeeeeeeeeeeeeeeeeeeeeeeeee"
      - run: |
          cd javaDemo/my-app
          mvn install 
  ciao:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fineeeeeeeeeeeeeeeeeeeeeeeeeeee2"